# Generated by Django 4.1.1 on 2022-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=16, null=True),
        ),
    ]
