# Generated by Django 4.1.1 on 2022-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uk', 'Украинский')], max_length=10, null=True),
        ),
    ]
