# Generated by Django 4.1.1 on 2022-11-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('phone_number',), ('email',), ('username',)},
        ),
    ]
