# Generated by Django 4.1.1 on 2022-11-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_ch_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
