# Generated by Django 4.1.1 on 2022-11-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('phone_number',), ('username',), ('email',)},
        ),
    ]
