# Generated by Django 4.1.1 on 2022-11-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='images/bg_banner/', verbose_name='')),
                ('color', models.CharField(blank=True, max_length=300)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=False)),
                ('interval', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('logo', models.ImageField(null=True, upload_to='images/pages/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/home_banner/', verbose_name='')),
                ('url', models.URLField(max_length=100)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/promo_banner/', verbose_name='')),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/pages/', verbose_name='')),
                ('active', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('type', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/news_events/', verbose_name='')),
                ('post_date', models.DateField()),
                ('video', models.URLField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/gallery_images/', verbose_name='')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('phone_0', models.IntegerField()),
                ('phone_1', models.IntegerField()),
                ('seo_text', models.TextField()),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/films/', verbose_name='')),
                ('premier_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('trailer', models.URLField(max_length=100)),
                ('v3d', models.BooleanField(default=False)),
                ('v2d', models.BooleanField(default=False)),
                ('imax', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('terms', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/cinema/', verbose_name='')),
                ('banner_image', models.ImageField(null=True, upload_to='images/cinema/', verbose_name='')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('scheme', models.ImageField(null=True, upload_to='images/hall/', verbose_name='')),
                ('image', models.ImageField(null=True, upload_to='images/hall/', verbose_name='')),
                ('date', models.DateField(null=True)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.cinema')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery')),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.seoblock')),
            ],
            options={
                'unique_together': {('name', 'cinema')},
            },
        ),
    ]
