# Generated by Django 4.1.1 on 2022-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
