# Generated by Django 4.1.1 on 2022-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_seance_date_alter_seance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
