# Generated by Django 4.1.1 on 2022-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_seance_cinema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
