# Generated by Django 4.1.1 on 2022-12-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_seance_type_alter_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='v2d',
            field=models.BooleanField(default=True),
        ),
    ]
