# Generated by Django 4.1.1 on 2022-12-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_alter_film_v2d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='films_id',
            new_name='film_id',
        ),
        migrations.RenameField(
            model_name='seance',
            old_name='halls_id',
            new_name='hall_id',
        ),
    ]
