# Generated by Django 4.1.1 on 2022-12-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_rename_films_id_seance_film_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='film_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
