# Generated by Django 4.1.1 on 2022-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_seance_film_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='hall_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
