# Generated by Django 4.1.1 on 2022-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_seance_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
