# Generated by Django 4.1.1 on 2022-12-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_seance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='scheme_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
