# Generated by Django 4.1.1 on 2022-12-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0021_alter_hall_scheme_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30, null=True)),
                ('booking', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('seance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_app.seance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('place', 'seance')},
            },
        ),
    ]
