# Generated by Django 4.1.1 on 2022-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_rename_booking_ticket_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
