# Generated by Django 4.1.1 on 2022-12-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_alter_ticket_seance_alter_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='scheme',
        ),
    ]
