# Generated by Django 4.1.1 on 2022-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_alter_cinemacontact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacontact',
            name='location',
            field=models.URLField(max_length=300),
        ),
    ]
