# Generated by Django 4.1.1 on 2022-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='terms_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='terms_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_ua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ru',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ua',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_text_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='name_ua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='description_ua',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='keywords_ua',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='seoblock',
            name='title_ua',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
