# Generated by Django 4.1.1 on 2022-12-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_cinema_description_ru_cinema_description_ua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='description_ua',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='keywords_ua',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='seoblock',
            name='title_ua',
        ),
    ]
