# Generated by Django 4.1.1 on 2022-12-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_remove_seoblock_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='name_ua',
        ),
    ]
