# Generated by Django 4.1.1 on 2022-12-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_remove_hall_name_ru_remove_hall_name_ua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='terms_ua',
            new_name='terms_uk',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='seo_text_ua',
            new_name='seo_text_uk',
        ),
        migrations.RenameField(
            model_name='newspromotions',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='newspromotions',
            old_name='name_ua',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description_ua',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
