# Generated by Django 4.1.1 on 2022-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_rename_description_ua_cinema_description_uk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='film_name',
            new_name='film_name_ru',
        ),
        migrations.AddField(
            model_name='seance',
            name='film_name_uk',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
