# Generated by Django 4.1.1 on 2022-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_rename_film_name_seance_film_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='film_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
