# Generated by Django 4.1.1 on 2022-12-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_seance_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacontact',
            name='location',
            field=models.TextField(),
        ),
    ]
