from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='admin'),
    path('movie/', movies, name='movies'),
    path('movie/<int:film_id>', show_film, name='film'),
    path('delete_film/<int:film_id>', delete_film, name='delete_film'),
    path('movie/page/', films_page, name='m_page'),
    path('banner/', banner, name='banner'),
    path('news/', news, name='news'),
    path('news/<int:news_id>', show_news, name='show_news'),
    path('delete_news/<int:news_id>', delete_news, name='delete_news'),
    path('news/page/', news_page, name='news_page'),
    path('events/', events, name='events'),
    path('events/<int:event_id>', show_events, name='show_events'),
    path('events/page/', events_page, name='events_page'),
    path('delete_event/<int:event_id>', delete_events, name='delete_events'),
    path('cinemas/', cinemas, name='cinemas_admin'),
    path('cinemas/page/', cinemas_page, name='cinemas_admin_page'),
    path('cinemas/<int:cinema_id>', show_cinema, name='cinema'),
    path('cinemas/<int:cinema_id>/hall_page/', hall_page, name='hall_page'),
    path('cinemas/<int:cinema_id>/<int:hall_id>/', show_hall, name='show_hall'),
    path('delete_cinema/<int:cinema_id>', delete_cinema, name='delete_cinema'),
    path('delete_hall/<int:cinema_id>/<int:hall_id>', delete_hall, name='delete_hall'),
    path('pages/', pages, name='pages'),
    path('pages/home_page/', home_page, name='home_page'),
    path('pages/contacts/', contacts, name='contacts'),
    path('pages/create_page/', create_page, name='create_page'),
    path('pages/<int:page_id>', show_page, name='show_page'),
    path('delete_page/<int:page_id>', delete_page, name='delete_page'),
    path('mailing/', mailing, name='mailing'),
    path('mailing/mailing_progress/<str:task_id>', mailing_progress, name='mailing_progress'),
    path('mailing/template_delete/<int:template_id>', template_delete, name='template_delete'),
    path('users/', users, name='users'),
    path('users/<int:user_id>', show_user, name='show_user_admin'),
    path('delete_user/<int:user_id>', delete_user, name='delete_user'),
    path('login', login_admin, name='login_admin'),
]