# Generated by Django 4.1.1 on 2022-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='films')),
                ('premier_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('trailer', models.URLField(max_length=100)),
                ('_3d', models.BooleanField(default=False)),
                ('_2d', models.BooleanField(default=True)),
                ('imax', models.BooleanField(default=False)),
            ],
        ),
    ]
