# Generated by Django 4.1.1 on 2022-12-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
